# Generated by Django 2.2.9 on 2020-02-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0007_delete_accelerationsensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('sensor_data', models.FloatField(default=0)),
            ],
        ),
    ]
