# Generated by Django 2.2.9 on 2020-02-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0008_randomsensor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindSpeedSensor',
        ),
    ]
