# Generated by Django 2.2.9 on 2020-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0009_delete_windspeedsensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccelerationSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('acceleration_x', models.FloatField(default=0)),
                ('acceleration_y', models.FloatField(default=0)),
                ('acceleration_z', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WindSpeedSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('wind_speed', models.FloatField(default=0)),
            ],
        ),
    ]
