# Generated by Django 2.2.9 on 2020-02-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0010_accelerationsensor_windspeedsensor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomSensor',
        ),
    ]
